
  CREATE TABLE "UDA4ULA"."FINES_FEES_LOAD" 
   (    "FF_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 0 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
    "INSTITUTIONAL_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
    "LIST" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
    "LOCATION" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
    "NOTE" VARCHAR2(80 BYTE) NOT NULL ENABLE, 
    "EMPLID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
    "CDS_ID" NUMBER(38,0) NOT NULL ENABLE, 
    "PRIMARY_NBR" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
     CONSTRAINT "FINES_FEES_PK" PRIMARY KEY ("FF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "USR_DATA_UD4"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "USR_DATA_UD4" ;

   COMMENT ON COLUMN "UDA4ULA"."FINES_FEES_LOAD"."FF_ID" IS 'Auto-incrementing primary key';
   COMMENT ON COLUMN "UDA4ULA"."FINES_FEES_LOAD"."INSTITUTIONAL_ID" IS 'The user''s raw institutional ID. CDS or 2P number.';
   COMMENT ON COLUMN "UDA4ULA"."FINES_FEES_LOAD"."LIST" IS 'The source list';
   COMMENT ON COLUMN "UDA4ULA"."FINES_FEES_LOAD"."LOCATION" IS 'The location, if one exists';
   COMMENT ON COLUMN "UDA4ULA"."FINES_FEES_LOAD"."EMPLID" IS 'The individual''s 2P ID.';
   COMMENT ON COLUMN "UDA4ULA"."FINES_FEES_LOAD"."CDS_ID" IS 'The individual''s CDS ID.';
   COMMENT ON COLUMN "UDA4ULA"."FINES_FEES_LOAD"."PRIMARY_NBR" IS 'The individual''s Peoplesoft ID.';

